#!/usr/bin/env python3
"""Wrap a static HTML file into a Cloudflare Worker ES module.

Reads an input HTML file, optionally inlines local asset references (images,
etc.) as base64 data-URIs so the Worker ships as a single self-contained file,
escapes the HTML for a JS template literal, and writes a `worker.mjs` module
that serves the page with a text/html content-type and a cache-control header.

Usage:
    python build_worker.py --html index.html --out worker.mjs --inline-assets
"""

import argparse
import base64
import mimetypes
import os
import re
import sys

# Attributes that can reference a local asset we may want to inline.
# Matches src="..." and href="..." (single or double quoted).
ASSET_ATTR_RE = re.compile(
    r"""(?P<attr>\b(?:src|href))\s*=\s*(?P<quote>["'])(?P<url>[^"']+)(?P=quote)""",
    re.IGNORECASE,
)

# These look like asset references but are not local files we should inline.
SKIP_PREFIXES = ("http://", "https://", "//", "data:", "mailto:", "tel:", "#")


def is_local_asset(url):
    """Return True if `url` points at a local file we could inline."""
    lowered = url.strip().lower()
    if not url.strip():
        return False
    return not lowered.startswith(SKIP_PREFIXES)


def inline_assets(html, base_dir):
    """Replace local asset references with base64 data-URIs.

    Only inlines files that exist on disk relative to `base_dir`. Anything
    remote, already a data-URI, or missing is left untouched.
    """

    def replace(match):
        url = match.group("url")
        if not is_local_asset(url):
            return match.group(0)

        # Strip any query string / fragment before resolving on disk.
        clean = url.split("?", 1)[0].split("#", 1)[0]
        asset_path = os.path.normpath(os.path.join(base_dir, clean))
        if not os.path.isfile(asset_path):
            print(f"  skip (not found): {url}", file=sys.stderr)
            return match.group(0)

        mime, _ = mimetypes.guess_type(asset_path)
        if mime is None:
            mime = "application/octet-stream"

        with open(asset_path, "rb") as fh:
            encoded = base64.b64encode(fh.read()).decode("ascii")

        data_uri = f"data:{mime};base64,{encoded}"
        print(f"  inlined: {url} ({mime}, {len(encoded)} b64 chars)", file=sys.stderr)
        return f'{match.group("attr")}={match.group("quote")}{data_uri}{match.group("quote")}'

    return ASSET_ATTR_RE.sub(replace, html)


def js_escape(html):
    """Escape HTML so it is safe inside a JS template literal.

    Order matters: escape backslashes first, then backticks, then the `${`
    sequence that JS would otherwise treat as an interpolation.
    """
    html = html.replace("\\", "\\\\")
    html = html.replace("`", "\\`")
    html = html.replace("${", "\\${")
    return html


WORKER_TEMPLATE = """\
// Generated by build_worker.py -- do not edit by hand.
// Serves a single static HTML page from the edge.
const HTML = `{html}`;

export default {{
  async fetch(request) {{
    return new Response(HTML, {{
      headers: {{
        "content-type": "text/html; charset=UTF-8",
        "cache-control": "public, max-age=300",
      }},
    }});
  }},
}};
"""


def build(html_path, out_path, do_inline):
    if not os.path.isfile(html_path):
        sys.exit(f"error: input HTML not found: {html_path}")

    with open(html_path, "r", encoding="utf-8") as fh:
        html = fh.read()

    if do_inline:
        base_dir = os.path.dirname(os.path.abspath(html_path))
        html = inline_assets(html, base_dir)

    worker = WORKER_TEMPLATE.format(html=js_escape(html))

    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(worker)

    print(f"wrote {out_path} ({len(worker)} bytes) from {html_path}")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Wrap a static HTML file into a Cloudflare Worker module."
    )
    parser.add_argument(
        "--html",
        default="index.html",
        help="path to the input HTML file (default: index.html)",
    )
    parser.add_argument(
        "--out",
        default="worker.mjs",
        help="path to write the Worker module (default: worker.mjs)",
    )
    parser.add_argument(
        "--inline-assets",
        action="store_true",
        help="inline local asset references (images, etc.) as base64 data-URIs",
    )
    args = parser.parse_args(argv)
    build(args.html, args.out, args.inline_assets)


if __name__ == "__main__":
    main()
